import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { GitWorktree, safePath, git } from '../src/adapters/git.js';
import { digest } from '../src/core/security.js';
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'cm-git-')),root=join(dir,'root');await mkdir(root);await git(root,['init','-b','main']);await git(root,['config','user.name','Test User']);await git(root,['config','user.email','test@example.invalid']);await writeFile(join(root,'hello.txt'),'before');await git(root,['add','.']);await git(root,['commit','-m','initial']);const base=await git(root,['rev-parse','HEAD']);return {dir,root,base,adapter:new GitWorktree(root,join(dir,'worktrees'))};}
test('路径逃逸、敏感路径与哈希错配阻止修改',async()=>{const {root,adapter}=await fixture();await assert.rejects(()=>safePath(root,'../escaped.txt'),/工作树/);await assert.rejects(()=>adapter.apply(root,[{path:'.env',content:'abc',originalHash:null}],[]),/敏感/);await assert.rejects(()=>adapter.apply(root,[{path:'hello.txt',content:'after',originalHash:digest('wrong')}],[]),/已变更/);assert.equal(await readFile(join(root,'hello.txt'),'utf8'),'before');});
test('结构化修改受目录范围限制，合法修改可提交',async()=>{const {root,base,adapter}=await fixture();await assert.rejects(()=>adapter.apply(root,[{path:'hello.txt',content:'after',originalHash:digest('before')}],['src']),/超出/);await adapter.apply(root,[{path:'hello.txt',content:'after',originalHash:digest('before')}],[]);const sha=await adapter.checkpoint(root,base,'checkpoint');assert.notEqual(sha,base);assert.equal(await readFile(join(root,'hello.txt'),'utf8'),'after');});
test('扫描含密钥的未跟踪文件并阻止提交',async()=>{const {root,base,adapter}=await fixture();await writeFile(join(root,'secret.txt'),'ghp_'+'x'.repeat(36));await assert.rejects(()=>adapter.checkpoint(root,base,'unsafe'),/凭据/);assert.equal(await git(root,['rev-parse','HEAD']),base);});
test('真实 Git worktree 修改不污染主工作区，push 不强推',async()=>{const {dir,root,base,adapter}=await fixture();const bare=join(dir,'remote.git');await mkdir(bare);await git(bare,['init','--bare']);await git(root,['remote','add','origin',bare]);await git(root,['push','origin','main']);const wt=await adapter.create('cm/42/user-r1','main','run1');await git(wt.path,['config','user.name','Test User']);await adapter.apply(wt.path,[{path:'hello.txt',content:'isolated',originalHash:digest('before')}],[]);const sha=await adapter.checkpoint(wt.path,base,'task');await adapter.push(wt.path,'cm/42/user-r1',base);assert.equal(await readFile(join(root,'hello.txt'),'utf8'),'before');assert.equal(await git(bare,['rev-parse','refs/heads/cm/42/user-r1']),sha);});
test('提交历史曾出现后又删除的秘密也阻止推送',async()=>{const {root,base,adapter}=await fixture();await writeFile(join(root,'history.txt'),'ghp_'+'z'.repeat(36));await git(root,['add','.']);await git(root,['commit','-m','bad']);await writeFile(join(root,'history.txt'),'removed');await git(root,['add','.']);await git(root,['commit','-m','remove']);await assert.rejects(()=>adapter.scan(root,base),/历史/);});
