import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { SquaresFour, Kanban, GitPullRequest, ArrowsLeftRight, TreeStructure, ChartBar, GearSix, Plus, ArrowUpRight, ArrowRight, ArrowClockwise, MagnifyingGlass, Bell, Check, X, CaretDown, GitBranch, ShieldCheck, Circle, Play, Pause, DotsThree, TerminalWindow, FolderSimple, Clock, CheckCircle, WarningCircle, LinkSimple, Command, DownloadSimple, ListChecks, Stack, CircleNotch, GithubLogo, Cube, SignOut } from '@phosphor-icons/react';
import { api, downloadExport, type Snapshot } from './api.js';
import type { Task, Project, Approval, Plan, Policy, ActionRequest } from '../core/model.js';
import './styles.css';
const names:Record<string,string>={ready:'待开始',needs_approval:'待审批',running:'进行中',review:'待审查',blocked:'已阻塞',handoff_pending:'待接力',done:'已完成',cancelled:'已取消',pending:'待确认',draft:'草稿',published:'已发布',stale:'已过期',accepted:'已接受',rejected:'已拒绝',completed:'已完成',executing:'执行中',failed:'失败',paused:'已暂停',frozen:'已冻结'};
const actionNames:Record<string,string>={run:'启动 Codex 任务',resume:'恢复本机任务',pause:'暂停任务',publish:'推送分支并创建草稿 PR',review:'启动只读 AI 审查',publish_review:'发布 AI 审查评论',handoff:'推送检查点并申请交接',accept_handoff:'接受交接并启动新线程',reject_handoff:'拒绝交接',repair:'按审查意见修复',plan:'生成 AI 规划草案',publish_plan:'创建规划中的 GitHub Issues',revert_plan:'关闭规划中尚未开始的 Issues',assign:'分配任务',init:'创建仓库配置与标签'};
const pages=[{id:'overview',label:'团队总览',icon:SquaresFour},{id:'tasks',label:'任务看板',icon:Kanban},{id:'reviews',label:'审查中心',icon:GitPullRequest},{id:'handoffs',label:'接力中心',icon:ArrowsLeftRight},{id:'planning',label:'协作规划',icon:TreeStructure},{id:'quality',label:'质量报告',icon:ChartBar}];
const time=(s?:string)=>s?new Date(s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未同步';
const short=(s:string)=>s.slice(0,8);
function Badge({state}:{state:string}){return <span className={'badge '+state}><span className="status-dot"/>{names[state]??state}</span>;}
function Empty({title,detail,children}:{title:string;detail?:string;children?:React.ReactNode}){return <div className="empty"><Stack size={34} weight="thin"/><h3>{title}</h3><p>{detail}</p>{children}</div>;}
function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current!;d.showModal();const onCancel=(e:Event)=>{e.preventDefault();onClose();};d.addEventListener('cancel',onCancel);return()=>{d.removeEventListener('cancel',onCancel);d.close();};},[]);return <dialog ref={ref} className={wide?'modal wide':'modal'} onClick={e=>{if(e.target===ref.current)onClose();}}><header><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20}/></button></header>{children}</dialog>;}
function Graph({tasks,onSelect}:{tasks:Task[];onSelect:(t:Task)=>void}){if(!tasks.length)return <Empty title="还没有任务依赖"/>;const visible=tasks.slice(0,16),w=740,h=Math.max(190,Math.ceil(visible.length/3)*104);const pos=new Map(visible.map((t,i)=>[t.issue,{x:20+(i%3)*245,y:25+Math.floor(i/3)*104}]));return <div className="graph"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="任务依赖图，箭头由前置任务指向后续任务"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#81958a"/></marker></defs>{visible.flatMap(t=>t.needs.map(n=>{const a=pos.get(n),b=pos.get(t.issue);return a&&b?<path key={`${n}-${t.issue}`} d={`M ${a.x+103} ${a.y+58} C ${a.x+103} ${a.y+90}, ${b.x+103} ${b.y-25}, ${b.x+103} ${b.y}`} stroke="#81958a" strokeWidth="1.5" fill="none" markerEnd="url(#arrow)"/>:null;}))}{visible.map(t=>{const p=pos.get(t.issue)!;return <g key={t.issue} tabIndex={0} role="button" aria-label={`任务 ${t.issue} ${t.title}`} onClick={()=>onSelect(t)} onKeyDown={e=>{if(e.key==='Enter')onSelect(t);}} className="graph-node"><rect x={p.x} y={p.y} width="210" height="58" rx="9"/><circle cx={p.x+17} cy={p.y+18} r="3" fill={t.state==='done'?'#3f8060':'#aaa998'}/><text x={p.x+28} y={p.y+22} className="graph-meta">#{t.issue} · {names[t.state]}</text><text x={p.x+13} y={p.y+44}>{t.title.length>15?t.title.slice(0,15)+'…':t.title}</text></g>;})}</svg><span className="graph-caption">前置任务 → 后续任务 · 依赖未完成时阻止启动</span></div>;}

function App(){
  const [data,setData]=useState<Snapshot>(),[page,setPage]=useState('overview'),[projectId,setProjectId]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState<Task>(),[modal,setModal]=useState<'connect'|'plan'|'notifications'|null>(null),[approval,setApproval]=useState<Approval>(),[logs,setLogs]=useState<string>(),[doctor,setDoctor]=useState<any>(),[policy,setPolicy]=useState<Policy>(),[mobileNav,setMobileNav]=useState(false);
  const search=useRef<HTMLInputElement>(null);
  async function refresh(){try{const next=await api<Snapshot>('/state');setData(next);setProjectId(v=>v||next.projects[0]?.id||'');}catch(e){setError(String(e));}}
  useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),4000);const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();search.current?.focus();}};window.addEventListener('keydown',key);return()=>{clearInterval(timer);window.removeEventListener('keydown',key);};},[]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
  const project=data?.projects.find(p=>p.id===projectId),tasks=(data?.tasks??[]).filter(t=>t.repoId===projectId&&(!query||`${t.issue} ${t.title} ${t.owner}`.toLowerCase().includes(query.toLowerCase()))),runs=(data?.runs??[]).filter(r=>r.repoId===projectId),reviews=(data?.reviews??[]).filter(r=>r.repoId===projectId),handoffs=(data?.handoffs??[]).filter(h=>h.repoId===projectId),plans=(data?.plans??[]).filter(p=>p.repoId===projectId),approvals=(data?.approvals??[]).filter(a=>a.repoId===projectId),pending=approvals.filter(a=>a.status==='pending'),audit=(data?.audit??[]).filter(a=>a.repoId===projectId);
  const title=pages.find(p=>p.id===page)?.label??({settings:'工作区设置',approvals:'本机审批'} as Record<string,string>)[page];
  async function perform(fn:()=>Promise<unknown>,message?:string){setBusy(true);setError('');try{await fn();if(message)setNotice(message);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function request(action:ActionRequest['action'],target:string,input:Record<string,unknown>={}){await perform(async()=>{const a=await api<Approval>('/actions',{method:'POST',body:JSON.stringify({repoId:projectId,action,target,input})});setTask(undefined);setModal(null);setApproval(a);});}
  async function decide(a:Approval,approved:boolean){await perform(async()=>{await api(`/approvals/${a.id}`,{method:'POST',body:JSON.stringify({approved})});setApproval(undefined);setPage('approvals');},approved?'已确认。执行结果会显示在审批记录中。':'已拒绝该操作。');}
  function nav(id:string){setPage(id);setMobileNav(false);setPolicy(undefined);}
  function taskRow(t:Task){return <button key={t.issue} className="task-row" onClick={()=>setTask(t)}><span className="issue mono">#{t.issue}</span><span className="task-row-title">{t.title}<small>{t.paths.join(' / ')||'待确认变更范围'}</small></span><Badge state={t.state}/><span className="assignee"><span className="avatar small">{t.owner?.slice(0,1).toUpperCase()||'–'}</span>{t.owner===project?.user?'我':t.owner||'未分配'}</span><ArrowUpRight size={16}/></button>;}
  function taskCard(t:Task){return <button className="task-card" key={t.issue} onClick={()=>setTask(t)}><div><span className="mono">#{t.issue}</span><span className={'priority '+t.priority}>{t.priority==='high'?'高优先级':t.priority==='low'?'低优先级':'常规'}</span></div><h3>{t.title}</h3><p>{t.acceptance[0]}</p><footer><span className="avatar small">{t.owner?.slice(0,1).toUpperCase()||'–'}</span><span>{t.owner||'待分配'}</span>{t.needs.length>0&&<span className="dependency"><LinkSimple size={13}/>{t.needs.length} 项依赖</span>}</footer></button>;}
  if(!data)return <div className="boot"><div className="logo-mark"><Command size={28}/></div><h2>CodexMate</h2><p>{error||'正在读取本机工作区…'}</p>{error?<button onClick={()=>void refresh()}>重试连接</button>:<div className="skeleton"/>}</div>;
  return <div className="app-shell">
    <aside className={'sidebar '+(mobileNav?'open':'')}><a className="brand" href="#" onClick={e=>{e.preventDefault();nav('overview');}}><span className="logo-mark"><Command size={23} weight="bold"/></span>CodexMate<span className="version">1.1</span></a>
      <div className="workspace-label">工作空间</div><label className="project-picker"><span className="project-icon"><Cube size={20}/></span><select aria-label="选择仓库" value={projectId} onChange={e=>{setProjectId(e.target.value);setTask(undefined);setPolicy(undefined);}}>{data.projects.length?data.projects.map(p=><option key={p.id} value={p.id}>{p.slug}</option>):<option value="">尚未连接仓库</option>}</select><CaretDown size={13}/></label>
      <nav aria-label="主导航">{pages.map(p=><button key={p.id} className={page===p.id?'active':''} onClick={()=>nav(p.id)}><p.icon size={19} weight={page===p.id?'duotone':'regular'}/><span>{p.label}</span>{p.id==='reviews'&&reviews.filter(r=>r.status==='draft').length>0&&<b>{reviews.filter(r=>r.status==='draft').length}</b>}{p.id==='handoffs'&&handoffs.filter(h=>h.status==='pending').length>0&&<b>{handoffs.filter(h=>h.status==='pending').length}</b>}</button>)}</nav>
      <div className="nav-divider"/><nav aria-label="工作区管理"><button className={page==='approvals'?'active':''} onClick={()=>nav('approvals')}><ShieldCheck size={19}/><span>本机审批</span>{pending.length>0&&<b className="attention">{pending.length}</b>}</button><button className={page==='settings'?'active':''} onClick={()=>nav('settings')}><GearSix size={19}/><span>工作区设置</span></button></nav>
      <div className="sidebar-bottom"><div className="local-card"><span className="status-dot"/><strong>本机优先，独立账户</strong><p>上下文可接力，凭据留在自己手中。</p><span><GitBranch size={13}/> GitHub 驱动的异步协作</span></div><button className="profile" onClick={()=>nav('settings')}><span className="avatar">{project?.user[0]?.toUpperCase()||'C'}</span><span><strong>{project?.user||'本机用户'}</strong><small>{project?.demo?'演练工作空间':'个人工作空间'}</small></span><GearSix size={16}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><button className="mobile-toggle icon-button" aria-label="打开导航" onClick={()=>setMobileNav(!mobileNav)}><SquaresFour size={22}/></button><div className="breadcrumb">工作空间<span>/</span><strong>{title}</strong></div><div className="top-tools"><label className="search"><MagnifyingGlass size={16}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索任务、编号…" aria-label="搜索任务"/><kbd>/</kbd></label><button className="icon-button notification-button" aria-label="查看通知" onClick={()=>setModal('notifications')}><Bell size={20}/>{data.notifications.length>0&&<i/>}</button><span className="avatar small">{project?.user[0]?.toUpperCase()||'C'}</span></div></header>
    <main>
      {project?.demo&&<div className="demo-banner"><Cube size={15}/><span>演练工作空间 · 数据仅用于体验，不调用 Codex 或写入 GitHub</span><button onClick={()=>setModal('connect')}>连接真实仓库 <ArrowRight size={14}/></button></div>}
      {error&&<div className="alert error" role="alert"><WarningCircle size={18}/><span>{error}</span><button className="icon-button" aria-label="关闭错误提示" onClick={()=>setError('')}><X size={17}/></button></div>}
      {project?.error&&<div className="alert error"><WarningCircle size={18}/><span>同步中断：当前显示缓存数据。{project.error}</span></div>}
      <div className="page-heading"><div><div className="eyebrow">{project?.slug??'YOUR LOCAL WORKSPACE'}</div><h1>{title}<span className="heading-dot">.</span></h1><p>{({overview:'连接彼此的工作，让每一次交接都有上下文。',tasks:'从一个明确的目标，到一份可审查的成果。',reviews:'以真实 diff 为依据，让每一条反馈可追溯。',handoffs:'带上代码检查点，把下一步交给队友。',planning:'先对齐目标与依赖，再确认开始。',quality:'看见实际执行的检查，保留未验证的边界。',settings:'让自动化按照你的规则运行。',approvals:'每个写入动作，都由你作出明确决定。'} as Record<string,string>)[page]}</p></div><div className="heading-actions"><button className="button secondary" disabled={busy||!project} onClick={()=>void perform(()=>api(`/projects/${projectId}/sync`,{method:'POST'}),'同步完成')}><ArrowClockwise size={16} className={busy?'spin':''}/>同步</button><button className="button primary" onClick={()=>setModal(page==='planning'?'plan':'connect')}><Plus size={16}/>{page==='planning'?'新建规划':'连接仓库'}</button></div></div>
      {!project?<section className="welcome"><div className="welcome-icon"><GitBranch size={46} weight="thin"/></div><h2>协作从连接一个仓库开始</h2><p>选择本机已克隆的 GitHub 仓库。CodexMate 会核验账号、仓库权限和默认分支配置。</p><button className="button primary" onClick={()=>setModal('connect')}><Plus size={16}/>连接本地仓库</button><div className="onboarding"><span>01 <strong>分别登录 gh 与 Codex</strong></span><ArrowRight/><span>02 <strong>连接共享仓库</strong></span><ArrowRight/><span>03 <strong>确认并启动任务</strong></span></div><code>gh auth login　·　codex login　·　codexmate doctor</code></section>:<>
      {page==='overview'&&<>
        <div className="overview-grid"><section className="welcome-panel"><div className="welcome-copy"><span className="panel-kicker"><span className="status-dot"/> WORK TOGETHER, LOCALLY</span><h2>各自专注，<br/>一起向前。</h2><p>{tasks.filter(t=>t.owner===project.user&&t.state==='ready').length?`你有 ${tasks.filter(t=>t.owner===project.user&&t.state==='ready').length} 个任务可以开始。`:'工作已对齐，随时开始下一步。'}<br/>每一份进展，都有迹可循。</p><button onClick={()=>nav('tasks')}>查看我的任务 <ArrowUpRight size={17}/></button></div><div className="flow-art" aria-label="Issue 到 Codex 到 PR 的协作流程"><div className="flow-orbit orbit-one"/><div className="flow-orbit orbit-two"/><div className="flow-node node-a"><GithubLogo size={23}/><span>Issue</span></div><div className="flow-node node-b"><Command size={29}/><span>Codex</span></div><div className="flow-node node-c"><GitPullRequest size={22}/><span>Pull request</span></div><svg viewBox="0 0 280 230" aria-hidden="true"><path d="M60 62 Q175 15 184 109 T92 195" fill="none" stroke="#6e9782" strokeDasharray="4 5"/></svg><span className="flow-caption"><ShieldCheck size={13}/> LOCAL FIRST</span></div></section>
        <section className="connection-panel"><div className="section-heading"><h2>工作区状态</h2><span className="tiny-tag">本机</span></div><div className="connection-row"><GithubLogo size={21}/><span><strong>GitHub</strong><small>{project.demo?'演练数据':project.lastSync?'最近同步成功':'等待同步核验'}</small></span><span className={'connection-dot '+(!project.error?'ok':'')}/></div><div className="connection-row"><Command size={21}/><span><strong>Codex</strong><small>{project.demo?'未调用 · 演练模式':'运行 doctor 核验本机登录'}</small></span><span className="tiny-tag">额度未知</span></div><div className="connection-footer"><span><Clock size={13}/> 最近同步</span><strong>{time(project.lastSync)}</strong></div><button className="text-button" onClick={()=>nav('settings')}>查看环境与策略 <ArrowRight size={14}/></button></section></div>
        <div className="stats-strip">{[{label:'进行中的任务',value:tasks.filter(t=>t.state==='running').length,icon:Circle,hint:'团队正在推进'},{label:'等待审查',value:reviews.filter(r=>r.status==='draft').length,icon:GitPullRequest,hint:'反馈让成果更可靠'},{label:'等待接力',value:handoffs.filter(h=>h.status==='pending').length,icon:ArrowsLeftRight,hint:'上下文已准备就绪'},{label:'待你确认',value:pending.length,icon:ShieldCheck,hint:'本机审批始终优先'}].map((s,i)=><button key={s.label} onClick={()=>nav(['tasks','reviews','handoffs','approvals'][i])}><div><s.icon size={17}/><span>{s.label}</span><ArrowUpRight size={14}/></div><strong>{String(s.value).padStart(2,'0')}</strong><small>{s.hint}</small></button>)}</div>
        <div className="content-grid"><section className="panel"><div className="section-heading"><h2>我的任务 <span>{tasks.filter(t=>t.owner===project.user&&!['done','cancelled'].includes(t.state)).length}</span></h2><button className="text-button" onClick={()=>nav('tasks')}>全部任务 <ArrowRight size={14}/></button></div><div className="table-head"><span>任务</span><span>状态</span><span>负责人</span></div>{tasks.filter(t=>t.owner===project.user&&!['done','cancelled'].includes(t.state)).slice(0,5).map(taskRow)}{!tasks.some(t=>t.owner===project.user)&&<Empty title="暂时没有分配给你的任务" detail="同步 GitHub，或从规划中心准备下一个目标。"/>}<div className="panel-footer"><ShieldCheck size={14}/>执行、推送与审查发布分别审批</div></section>
        <section className="panel activity"><div className="section-heading"><h2>最近动态</h2><span className="tiny-tag">本机记录</span></div>{audit.slice(0,5).map(a=><div className="activity-item" key={a.id}><span className="activity-icon"><GitBranch size={14}/></span><div><strong>{({'demo.created':'演练工作区已就绪','approval.requested':'新的操作等待确认','approval.granted':'已确认执行操作','action.completed':'受管操作已完成','sync.completed':'仓库状态已同步','project.connected':'仓库连接已建立','policy.updated':'本机策略已更新'} as Record<string,string>)[a.action]??a.action}</strong><p>{a.detail.slice(0,76)}</p><time>{time(a.at)}</time></div></div>)}{!audit.length&&<Empty title="还没有活动"/>}</section></div>
        <section className="team-bar"><div><span className="avatar-stack">{project.members.map(m=><span className="avatar small" key={m.login}>{m.login[0].toUpperCase()}</span>)}</span><strong>{project.members.length} 位协作者</strong><span>独立账户 · 通过 GitHub 异步协作</span></div><span><ShieldCheck size={14}/> 不共享凭据，不合并额度</span></section>
      </>}
      {page==='tasks'&&<><div className="view-toolbar"><div className="segmented"><span className="selected"><Kanban size={15}/>看板视图</span></div><span>{tasks.length} 个任务 · 点击查看详情与操作</span></div><div className="board">{['ready','running','review','blocked','done'].map(state=><section className="board-column" key={state}><header><span className={'status-dot '+state}/><h2>{names[state]}</h2><span>{tasks.filter(t=>(state==='blocked'?['blocked','needs_approval','handoff_pending']:state==='done'?['done','cancelled']:[state]).includes(t.state)).length}</span></header>{tasks.filter(t=>(state==='blocked'?['blocked','needs_approval','handoff_pending']:state==='done'?['done','cancelled']:[state]).includes(t.state)).map(taskCard)}<div className="board-end">{state==='ready'?'清晰的目标是协作的开始':'暂无更多任务'}</div></section>)}</div><section className="panel graph-section"><div className="section-heading"><h2>任务依赖</h2><span className="tiny-tag">方向表示前置关系</span></div><Graph tasks={tasks} onSelect={setTask}/></section>{data.conflicts.filter(c=>tasks.some(t=>t.issue===c.a)).map(c=><div className="alert" key={`${c.a}-${c.b}`}><WarningCircle size={18}/>#{c.a} 与 #{c.b} 可能同时修改 {c.paths.join('、')}，建议串行处理或先对齐接口。</div>)}</>}
      {page==='reviews'&&<><div className="view-toolbar"><span>审查绑定精确提交 SHA，PR 更新后需要重新审查。</span><form className="inline-form" onSubmit={e=>{e.preventDefault();void request('review',String(new FormData(e.currentTarget).get('pr')));}}><input name="pr" type="number" min="1" required aria-label="PR 编号" placeholder="PR 编号"/><button className="button secondary" disabled={busy}><Plus size={14}/>新建审查</button></form></div><div className="document-list">{reviews.map(r=><article className="panel document" key={r.id}><header><span className="document-icon"><GitPullRequest size={22}/></span><div><span className="eyebrow">PULL REQUEST #{r.pr}</span><h2>{r.title}</h2></div><Badge state={r.status}/></header><div className="document-meta"><span className="mono"><GitBranch size={13}/>{short(r.head)}</span><span>{time(r.createdAt)}</span><a href={r.url} target="_blank" rel="noreferrer">原始 PR <ArrowUpRight size={13}/></a></div><pre className="review-body">{r.body}</pre><footer><span><ShieldCheck size={14}/>仅发布评论，不自动 Approve 或合并</span><button className="button primary" disabled={r.status!=='draft'||busy} onClick={()=>void request('publish_review',r.id)}>预览并发布 <ArrowUpRight size={14}/></button></footer></article>)}</div>{!reviews.length&&<Empty title="还没有审查记录" detail="输入 PR 编号，确认后使用本人 Codex 进行只读审查。"/>}</>}
      {page==='handoffs'&&<>{handoffs.map(h=><article className="panel document handoff" key={h.id}><header><span className="document-icon"><ArrowsLeftRight size={22}/></span><div><span className="eyebrow">任务 #{h.issue} · REV {h.revision}</span><h2>{h.goal}</h2></div><Badge state={h.status}/></header><div className="handoff-people"><span className="avatar">{h.from[0].toUpperCase()}</span><strong>{h.from}</strong><span className="handoff-line"/><ArrowRight size={18}/><span className="handoff-line"/><span className="avatar">{h.to[0].toUpperCase()}</span><strong>{h.to===project.user?'我':h.to}</strong><span className="muted">新的本机线程 · 独立账户</span></div><div className="handoff-grid"><div><h3>检查点与验收</h3><code>{h.sha}</code><p className="mono">{h.branch}</p>{h.acceptance.map((x,i)=><p key={i} className="checkline"><ListChecks size={15}/>{x}</p>)}<small>实际检查：{h.checks.length?h.checks.map(c=>`${c.name} (${c.exitCode})`).join('、'):'未运行'}</small></div><div><h3>接下来要做</h3>{h.remaining.map((x,i)=><p key={i} className="checkline"><Circle size={12}/>{x}</p>)}<div className="risk-note"><WarningCircle size={15}/>{h.risks.join('；')||'暂无已记录风险'}</div></div></div><footer><span>接受后从精确 SHA 新建线程，不迁移原对话。</span><div><button className="button secondary" disabled={h.status!=='pending'||h.to!==project.user} onClick={()=>void request('reject_handoff',h.id)}>拒绝</button><button className="button primary" disabled={h.status!=='pending'||h.to!==project.user} onClick={()=>void request('accept_handoff',h.id)}>检查并接受 <ArrowRight size={15}/></button></div></footer></article>)}{!handoffs.length&&<Empty title="所有工作都在各自推进" detail="打开任务详情，可以将安全检查点交给队友。"/>}</>}
      {page==='planning'&&<><section className="planning-intro"><div className="planning-symbol"><TreeStructure size={35} weight="thin"/></div><div><h2>先把目标，变成共同的路线。</h2><p>生成拆分建议、验收标准与依赖。你确认后，才会在 GitHub 创建任务。</p></div><button className="button primary" onClick={()=>setModal('plan')}><Plus size={16}/>新建规划</button></section>{plans.map(p=><article className="panel document" key={p.id}><header><div><span className="eyebrow">协作规划 · {time(p.createdAt)}</span><h2>{p.goal}</h2></div><Badge state={p.status==='reverted'?'cancelled':p.status}/></header><ol className="plan-list">{p.tasks.map((t,i)=><li key={i}><span className="plan-index">{String(i+1).padStart(2,'0')}</span><div><h3>{t.title}</h3><p>{t.acceptance.join('；')}</p><small>涉及 {t.paths.join('、')||'待确认'} · {t.needs.length?`依赖任务 ${t.needs.map(n=>n+1).join('、')}`:'可独立开始'}</small><p className="evidence">依据：{t.evidence}</p></div></li>)}</ol><footer><span>草案仅是建议，发布前请核对范围、依据和分工。</span><button className="button primary" disabled={p.status==='reverted'} onClick={()=>void request(p.status==='draft'?'publish_plan':'revert_plan',p.id)}>{p.status==='draft'?'确认创建任务':'撤销未开始的任务'}<ArrowRight size={15}/></button></footer></article>)}{!plans.length&&<Empty title="你的下一个目标，从这里拆解" detail="提供明确目标和验收条件，让任务之间的关系先清晰起来。"/>}<section className="panel graph-section"><div className="section-heading"><h2>当前任务关系</h2><span className="tiny-tag">来自任务声明</span></div><Graph tasks={tasks} onSelect={setTask}/></section></>}
      {page==='quality'&&<><div className="quality-heading"><ShieldCheck size={30} weight="duotone"/><div><h2>真实记录，不做自评分</h2><p>以下数字来自本机 Run 与检查结果。{project.demo?'当前为演练环境，无真实测试结果。':'未运行的检查不会计入通过率。'}</p></div><button className="button secondary" onClick={()=>void perform(()=>downloadExport(true),'已导出脱敏记录')}><DownloadSimple size={16}/>导出报告</button></div><div className="stats-strip">{[{label:'已记录运行',value:runs.length},{label:'实际检查',value:runs.flatMap(r=>r.checks).length},{label:'检查通过',value:runs.flatMap(r=>r.checks).filter(c=>c.exitCode===0).length},{label:'检查失败',value:runs.flatMap(r=>r.checks).filter(c=>c.exitCode!==0).length}].map(x=><div key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>本机可追溯记录</small></div>)}</div><section className="panel"><div className="section-heading"><h2>运行与验证记录</h2><span className="tiny-tag">不代表整个团队</span></div>{runs.map(r=><div className="run-row" key={r.id}><span className="mono">#{r.issue}</span><div><strong>{r.summary?.slice(0,70)||'等待运行摘要'}</strong><small>{time(r.startedAt)} · {r.checks.length?`${r.checks.length} 项检查`:'未运行检查'}</small></div><Badge state={r.status}/><button className="text-button" onClick={()=>void perform(async()=>setLogs((await api<{text:string}>(`/runs/${r.id}/logs`)).text))}>日志 <ArrowUpRight size={13}/></button></div>)}{!runs.length&&<Empty title="还没有可以统计的执行记录" detail="完成一次任务后，这里会展示实际运行与检查结果。"/>}</section><section className="panel"><div className="section-heading"><h2>建议优先回归的检查</h2></div>{runs.flatMap(r=>r.checks.filter(c=>c.exitCode!==0).map(c=><div className="failure-row" key={`${r.id}-${c.name}`}><WarningCircle size={18}/><div><strong>{c.name}</strong><p>任务 #{r.issue} · 失败于 {time(c.at)}</p><pre>{c.output.slice(-700)}</pre></div></div>))}{!runs.some(r=>r.checks.some(c=>c.exitCode!==0))&&<Empty title="暂无已记录的失败模式" detail="有实际失败证据后，才会生成回归优先级建议。"/>}</section></>}
      {page==='approvals'&&<><div className="view-toolbar"><span><ShieldCheck size={16}/> 审批绑定任务版本、内容与本机策略，15 分钟后过期。</span><span>{pending.length} 条待处理</span></div>{approvals.slice().reverse().map(a=><article className="panel approval-row" key={a.id}><div className="document-icon"><ShieldCheck size={22}/></div><div><h3>{actionNames[a.action]}</h3><p>目标 {a.target} · {time(a.createdAt)}</p>{a.result&&<pre className={a.status==='failed'?'failed-text':''}>{a.result}</pre>}</div><Badge state={a.status}/><button className="button secondary" disabled={a.status!=='pending'} onClick={()=>setApproval(a)}>查看申请 <ArrowUpRight size={14}/></button></article>)}{!approvals.length&&<Empty title="没有等待你的决定" detail="从任务、审查或接力中心发起操作后，申请会出现在这里。"/>}</>}
      {page==='settings'&&<><section className="panel settings-panel"><div className="section-heading"><h2>仓库与身份</h2><GithubLogo size={20}/></div><div className="settings-info"><div><small>已绑定仓库</small><strong>{project.slug}</strong></div><div><small>GitHub 身份</small><strong>@{project.user}</strong></div><div><small>角色</small><strong>{({owner:'维护者',developer:'开发者',reviewer:'审查者',viewer:'观察者'})[project.role]}</strong></div><div><small>协作模式</small><strong>GitHub 原生协作</strong></div></div><p className="device-id">本机设备 <code>{data.device}</code></p><p className="muted">活跃 Worker：{project.activeDevice===data.device?'此设备':project.activeDevice||'未指定，需维护者配置默认分支 workers'}</p><div className="settings-actions"><button className="button secondary" disabled={busy} onClick={()=>void perform(async()=>setDoctor(await api('/doctor')))}><TerminalWindow size={16}/>检查运行环境</button><button className="button secondary" disabled={project.demo} onClick={()=>void request('init','config')}>初始化仓库配置</button><button className="button secondary" onClick={()=>void perform(()=>api('/maintenance/recover',{method:'POST'}),'已检查中断的本机运行')}>恢复对账</button></div>{doctor&&<div className="doctor-results">{doctor.checks.map((c:any)=><div key={c.name}>{c.ok?<CheckCircle size={18}/>:<WarningCircle size={18}/>}<strong>{c.name}</strong><pre>{c.detail}</pre></div>)}<p>{doctor.authMode} · 剩余额度：{doctor.quota}</p></div>}</section>
      <form className="panel settings-panel" onSubmit={e=>{e.preventDefault();void perform(()=>api(`/projects/${projectId}/settings`,{method:'PUT',body:JSON.stringify(policy??project.policy)}),'本机策略已保存');}}><div className="section-heading"><h2>执行与审批策略</h2><span className="tiny-tag">仅作用于此仓库 / 此设备</span></div>{[{key:'autoStart',title:'自动启动分配给我的低风险任务',detail:'开启后，前台 Worker 可以启动本人任务。依赖、设备和权限检查仍然生效。'},{key:'autoPush',title:'自动推送并创建草稿 PR',detail:'仅在自动执行完成、扫描通过后生效。不会合并或部署。'},{key:'notifications',title:'本机协作通知',detail:'任务、审批、接力与失败通知在工作台中去重展示。'}].map(x=><label className="toggle-row" key={x.key}><span><strong>{x.title}</strong><small>{x.detail}</small></span><input type="checkbox" checked={Boolean((policy??project.policy)[x.key as keyof Policy])} onChange={e=>setPolicy({...policy??project.policy,[x.key]:e.target.checked})}/></label>)}<div className="settings-fields"><label>轮询间隔（秒）<input type="number" min="30" max="3600" value={(policy??project.policy).pollingSeconds} onChange={e=>setPolicy({...policy??project.policy,pollingSeconds:Number(e.target.value)})}/></label><label>任务超时（分钟）<input type="number" min="1" max="180" value={(policy??project.policy).timeoutMinutes} onChange={e=>setPolicy({...policy??project.policy,timeoutMinutes:Number(e.target.value)})}/></label><label>最多修复轮次<input type="number" min="0" max="2" value={(policy??project.policy).maxRepairAttempts} onChange={e=>setPolicy({...policy??project.policy,maxRepairAttempts:Number(e.target.value)})}/></label><label>日志保留（天）<input type="number" min="1" max="365" value={(policy??project.policy).retentionDays} onChange={e=>setPolicy({...policy??project.policy,retentionDays:Number(e.target.value)})}/></label></div><footer><span className="muted">保存即表示你授权所选自动化范围；可随时关闭。</span><button className="button primary" disabled={busy||!policy}><Check size={16}/>保存本机策略</button></footer></form>
      <section className="panel settings-panel"><div className="section-heading"><h2>数据与隐私</h2><ShieldCheck size={20}/></div><p>运行日志、线程标识和审批记录保存在本机。GitHub 上已发布的评论不会随本机清理而消失。</p><div className="settings-actions"><button className="button secondary" onClick={()=>void perform(()=>downloadExport(true),'已导出脱敏记录')}><DownloadSimple size={16}/>导出脱敏记录</button><button className="button secondary" onClick={()=>void perform(()=>api('/maintenance/prune',{method:'POST'}),'过期运行日志已清理，工作树与历史记录已保留')}>清理过期日志</button></div></section></>}
      </>}
      <footer className="page-footer"><span>CodexMate <span className="mono">v1.1.0-rc.1</span></span><span><span className="status-dot"/> 本机工作台 · 不上传遥测</span></footer>
    </main></div>
    {notice&&<div className="toast" role="status"><CheckCircle size={20}/>{notice}</div>}
    {modal==='connect'&&<Modal title="连接 GitHub 仓库" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();const root=new FormData(e.currentTarget).get('root');void perform(async()=>{const p=await api<Project>('/projects',{method:'POST',body:JSON.stringify({root})});setProjectId(p.id);setModal(null);},'仓库已连接。请同步任务或初始化配置。');}}><p className="modal-description">选择已克隆到本机的仓库根目录。使用你当前的 gh 账号核验身份和权限。</p><label className="field">本地仓库完整路径<input autoFocus name="root" required placeholder="例如 E:\projects\my-repository"/></label><div className="info-note"><ShieldCheck size={18}/><span>这里只连接仓库。初始化标签、执行任务或推送代码会分别请求确认。</span></div><footer><button type="button" className="button secondary" onClick={()=>setModal(null)}>取消</button><button className="button primary" disabled={busy}>{busy?<CircleNotch className="spin"/>:<LinkSimple size={16}/>}连接并核验</button></footer></form></Modal>}
    {modal==='plan'&&<Modal title="创建协作规划" onClose={()=>setModal(null)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void request('plan','new',{goal:f.get('goal'),acceptance:f.get('acceptance')});}}><p className="modal-description">先生成可审查的拆分草案，确认发布后才会创建 Issue。</p><label className="field">想要完成的目标<input autoFocus name="goal" required maxLength={500} placeholder="例如：为产品添加可追溯的通知中心"/></label><label className="field">可以验证的验收条件<textarea name="acceptance" required rows={4} placeholder="例如：支持通知去重、已读标记；重启后状态保留；有回归用例"/></label><footer><button type="button" className="button secondary" onClick={()=>setModal(null)}>取消</button><button className="button primary" disabled={busy}>预览运行申请 <ArrowRight size={16}/></button></footer></form></Modal>}
    {modal==='notifications'&&<Modal title="协作通知" onClose={()=>setModal(null)}>{data.notifications.length?(data.notifications as any[]).map(n=><div className="notification-item" key={n.id}><Bell size={18}/><div><h3>{n.title}</h3><p>{n.detail}</p><small>{time(n.at)}</small></div><button className="icon-button" aria-label="清除通知" onClick={()=>void perform(()=>api(`/notifications/${encodeURIComponent(n.id)}`,{method:'DELETE'}))}><Check size={16}/></button></div>):<Empty title="暂时没有新通知" detail="任务和协作变化会在这里提醒你。"/>}</Modal>}
    {task&&<Modal wide title={`#${task.issue} ${task.title}`} onClose={()=>setTask(undefined)}><div className="task-detail"><div className="detail-meta"><Badge state={task.state}/><span>@{task.owner||'未分配'}</span><span className="mono">Revision {task.revision}</span><a href={task.url} target="_blank" rel="noreferrer">GitHub 原始记录 <ArrowUpRight size={14}/></a></div><p>{task.body}</p>{task.warning&&<div className="alert error">{task.warning}</div>}<h3>验收条件</h3><ul className="acceptance">{task.acceptance.map((x,i)=><li key={i}><ListChecks size={17}/>{x}</li>)}</ul><div className="detail-grid"><div><h3>变更范围</h3>{task.paths.map(p=><code key={p}>{p}</code>)}{!task.paths.length&&<span>未声明，启动前请核对任务范围。</span>}</div><div><h3>前置任务</h3>{task.needs.length?task.needs.map(n=><button className="chip" key={n} onClick={()=>setTask(data.tasks.find(t=>t.repoId===task.repoId&&t.issue===n))}>#{n}</button>):<span>无前置依赖</span>}</div></div><h3>本机运行</h3>{runs.filter(r=>r.issue===task.issue).map(r=><div className="run-detail" key={r.id}><Badge state={r.status}/><code>{r.branch}</code><p>{r.summary||r.error||'等待运行摘要'}</p><p className="path">{r.worktree}</p><button className="text-button" onClick={()=>void perform(async()=>setLogs((await api<{text:string}>(`/runs/${r.id}/logs`)).text))}>查看本机日志 <ArrowUpRight size={13}/></button></div>)}{!runs.some(r=>r.issue===task.issue)&&<p className="muted">尚未在本机执行。</p>}<div className="task-actions">{task.owner===project?.user&&<><button className="button primary" disabled={busy} onClick={()=>void request(runs.some(r=>r.issue===task.issue)?'resume':'run',String(task.issue))}><Play size={16}/>启动 / 继续</button><button className="button secondary" onClick={()=>void request('publish',String(task.issue))}><GitPullRequest size={16}/>发布草稿 PR</button><button className="button secondary" onClick={()=>void request('pause',String(task.issue))}><Pause size={16}/>暂停</button><form className="inline-form" onSubmit={e=>{e.preventDefault();void request('handoff',String(task.issue),{to:new FormData(e.currentTarget).get('to')});}}><select name="to" aria-label="接手者">{project?.members.filter(m=>m.login!==project.user).map(m=><option key={m.login}>{m.login}</option>)}</select><button className="button secondary"><ArrowsLeftRight size={16}/>交接</button></form></>}{!task.owner&&<form className="inline-form" onSubmit={e=>{e.preventDefault();void request('assign',String(task.issue),{owner:new FormData(e.currentTarget).get('owner')});}}><select name="owner" aria-label="任务负责人">{project?.members.map(m=><option key={m.login}>{m.login}</option>)}</select><button className="button primary">确认分配</button></form>}</div></div></Modal>}
    {approval&&<Modal title="确认本机操作" onClose={()=>setApproval(undefined)}><div className="approval-preview"><div className="approval-symbol"><ShieldCheck size={30}/></div><h3>{actionNames[approval.action]}</h3><p>仓库：{project?.slug}<br/>目标：{approval.target}<br/>有效至：{time(approval.expiresAt)}</p>{Object.keys(approval.input).length>0&&<pre>{JSON.stringify(approval.input,null,2)}</pre>}<div className="info-note"><ShieldCheck size={18}/><span>{project?.demo?'此操作仅更新独立演练数据，不调用 Codex 或 GitHub。':'你将授权上述具体操作。执行前会复核身份、任务版本与本机策略；失败原因会保留在审批记录。'}</span></div><p className="muted">确认依据 <code>{approval.digest.slice(0,16)}</code></p></div><footer><button className="button secondary" disabled={busy} onClick={()=>void decide(approval,false)}>拒绝本次操作</button><button className="button primary" disabled={busy} onClick={()=>void decide(approval,true)}><Check size={16}/>确认执行</button></footer></Modal>}
    {logs!==undefined&&<Modal wide title="本机运行日志 · 已脱敏" onClose={()=>setLogs(undefined)}><pre className="log-view">{logs}</pre></Modal>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
